#pragma once
#pragma comment(lib, "ippicvmt.lib")
#ifdef NDEBUG
#pragma comment(lib, "libjpeg-turbo.lib")
#pragma comment(lib, "IlmImf.lib")
#pragma comment(lib, "ippiw.lib")
#pragma comment(lib, "libpng.lib")
#pragma comment(lib, "libtiff.lib")
#pragma comment(lib, "ittnotify.lib")
#pragma comment(lib, "zlib.lib")
#pragma comment(lib, "libwebp.lib")
#pragma comment(lib, "libjasper.lib")
#pragma comment(lib, "opencv_core411.lib")
#pragma comment(lib, "opencv_highgui411.lib")
#pragma comment(lib, "opencv_imgproc411.lib")
#pragma comment(lib, "opencv_imgcodecs411.lib")
#else
#pragma comment(lib, "libjpeg-turbod.lib")
#pragma comment(lib, "IlmImfd.lib")
#pragma comment(lib, "ippiwd.lib")
#pragma comment(lib, "libpngd.lib")
#pragma comment(lib, "libtiffd.lib")
#pragma comment(lib, "ittnotifyd.lib")
#pragma comment(lib, "zlibd.lib")
#pragma comment(lib, "libwebpd.lib")
#pragma comment(lib, "libjasperd.lib")
#pragma comment(lib, "opencv_core411d.lib")
#pragma comment(lib, "opencv_highgui411d.lib")
#pragma comment(lib, "opencv_imgproc411d.lib")
#pragma comment(lib, "opencv_imgcodecs411d.lib")
#endif